global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "earth-impact-live"
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets:
          - "earth-impact-live-12345.azurewebsites.net"
